apiVersion: v1
kind: Service
metadata:
  name: kittens-carousel-server
  labels:
    name: kittens-carousel-server-service
    app: kittens-carousel-app
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort
  #type: LoadBalancer
  selector:
     name: kittens-carousel-pod
     app: kittens-carousel-app