apiVersion: v1
kind: PersistentVolume
metadata:
  name: kittens-pv-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/Users/aydin/Desktop/Kubernetes/Project-101-kittens-carousel-static-website-ec2-nginx"