apiVersion: v1
kind: Pod
metadata:
  name: kittens-pod
  labels:
    name: kittens-pod
    app: kittens-website-app
spec:
  volumes:
    - name: kittens-pv-storage
      persistentVolumeClaim:
        claimName: kittens-pv-claim
  containers:
    - name: kittens
      image: aydintokuslu/kittens_website:1.0
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: kittens-pv-storage
