apiVersion: v1
kind: Service
metadata:
  name: kittens-server
  labels:
    name: kittens-server-service
    app: kittens-website-app
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort
  #type: LoadBalancer
  selector:
     name: kittens-pod
     app: kittens-website-app