apiVersion: v1
kind: PersistentVolume
metadata:
  name: roman-numerals-pv-vol
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/Users/aydin/Desktop/Kubernetes/Project-001-Roman-Numerals-Converter"