apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    name: mysql-service
    app: bookstore-api-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
     name: mysql-pod
     app: bookstore-api-app
  