apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UDEyMzQ1NnA=
  MYSQL_DATABASE: Ym9va3N0b3JlX2Ri
  MYSQL_USER: Y2xhcnVzd2F5
  MYSQL_PASSWORD: Q2xhcnVzd2F5XzE=

  